services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: accountant-web
    container_name: accountant-web-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:XG8o34J27I+Z1PZyIfQyA2Xv8zN6U0gXYQkV+F/Uv0A=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
    networks:
      - accountant-network

networks:
  accountant-network:
    driver: bridge
